name: Deploy to Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Pages
    uses: bigbang1112/workflows/.github/workflows/deploy-pages.yml@main
    with:
      dotnet-version: 10.x.x
      project: BlazorWasmOfflineSample
